// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEEbEOgjz54V36lH9g9XUngIP7BdZBY4U',
    appId: '1:1096161905872:web:598bbcd87166d2ebb422d5',
    messagingSenderId: '1096161905872',
    projectId: 'roundnetboard',
    authDomain: 'roundnetboard.firebaseapp.com',
    storageBucket: 'roundnetboard.firebasestorage.app',
    measurementId: 'G-M874V4T7G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5d40Zj9_SIObEpAw_JbACKm9APJR0ToI',
    appId: '1:1096161905872:android:c5e8f33482f99701b422d5',
    messagingSenderId: '1096161905872',
    projectId: 'roundnetboard',
    storageBucket: 'roundnetboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF5Ic60w4ZYFHmBnAfnbigFfMlrdpoFNA',
    appId: '1:1096161905872:ios:ee82a6ddae584400b422d5',
    messagingSenderId: '1096161905872',
    projectId: 'roundnetboard',
    storageBucket: 'roundnetboard.firebasestorage.app',
    iosBundleId: 'com.moritzberg.roundnetboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF5Ic60w4ZYFHmBnAfnbigFfMlrdpoFNA',
    appId: '1:1096161905872:ios:ee82a6ddae584400b422d5',
    messagingSenderId: '1096161905872',
    projectId: 'roundnetboard',
    storageBucket: 'roundnetboard.firebasestorage.app',
    iosBundleId: 'com.moritzberg.roundnetboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEEbEOgjz54V36lH9g9XUngIP7BdZBY4U',
    appId: '1:1096161905872:web:04e394b293310b5fb422d5',
    messagingSenderId: '1096161905872',
    projectId: 'roundnetboard',
    authDomain: 'roundnetboard.firebaseapp.com',
    storageBucket: 'roundnetboard.firebasestorage.app',
    measurementId: 'G-0P2ZJLZB3Z',
  );
}
