extend type Query {
  """
  ✨ Look up a single `Animation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  animation(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Animation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Animation_FirstRow
  ): Animation @fdc_generated(from: "Animation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `AnimationFrame` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  animationFrame(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AnimationFrame_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AnimationFrame_FirstRow
  ): AnimationFrame @fdc_generated(from: "AnimationFrame", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Board` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  board(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Board_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Board_FirstRow
  ): Board @fdc_generated(from: "Board", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `BoardElement` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  boardElement(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: BoardElement_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: BoardElement_FirstRow
  ): BoardElement @fdc_generated(from: "BoardElement", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `Animation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  animations(
    """
    Filter condition to narrow down the query results.
    """
    where: Animation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Animation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Animation_Having
  ): [Animation!]! @fdc_generated(from: "Animation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `AnimationFrame` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  animationFrames(
    """
    Filter condition to narrow down the query results.
    """
    where: AnimationFrame_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AnimationFrame_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AnimationFrame_Having
  ): [AnimationFrame!]! @fdc_generated(from: "AnimationFrame", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Board` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  boards(
    """
    Filter condition to narrow down the query results.
    """
    where: Board_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Board_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Board_Having
  ): [Board!]! @fdc_generated(from: "Board", purpose: QUERY_MULTIPLE)
  """
  ✨ List `BoardElement` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  boardElements(
    """
    Filter condition to narrow down the query results.
    """
    where: BoardElement_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [BoardElement_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: BoardElement_Having
  ): [BoardElement!]! @fdc_generated(from: "BoardElement", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
